### ISSUE TITLE
Move to github actions

### ISSUE THREAD

**Issue by kboshold** [xpublisher/xformatting#24]
**Xformat Version:** 1.2.0

**Type of report:**
- [ ] BUG
- [X] FEATURE
- [ ] OTHER

**Expected behavior:**
Moving the pipeline to Github Actions
Activate Dependabot (Automatic PR once a week?)

**Actual behavior:**
Travis is used

**Comment by Jimmy-653** [comment]
It seems there's a problem with the before step. Maybe you can figure this one out more easily: https://github.com/J-Jimmy/xformatting/runs/3846179507?check_suite_focus=true

**Comment by Jimmy-653** [comment]
Github actions workflow is added, but you have to activate dependabot for this repo since I don't have that permission
